prepare:
  split: 0.20
  seed: 42

train:
  feature_columns:
  - SepalLengthCm
  - SepalWidthCm
  model:
    name: random_forest
    params:
      n_estimators: 10
      random_state: 42
      max_depth: 3

